"""Added few fields

Revision ID: 72e7d68717f7
Revises: 050ba5e83aff
Create Date: 2024-10-30 18:32:17.975357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e7d68717f7'
down_revision: Union[str, None] = '050ba5e83aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('solver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['solver_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'solver_id')
    # ### end Alembic commands ###
